name: SpoutTrade
author: Arkel (Oliver Brown)
main: net.ark3l.SpoutTrade.SpoutTrade
version: 1.5.0
commands:
  trade:
    description: Trade with another player
    aliases: spouttrade
    usage: /trade <player>
permissions:
  spouttrade.*:
    description: Allows access to all SpoutTrade commands
    default: op
  spouttrade.trade:
    description: Allows players to trade using SpoutTrade
    default: true
