# Allows players to right click to initiate a trade request
RightClickTrade: true
# Force players to be within the specified distance to trade
RangeCheck:
    Enabled: true
    MaxDistance: 20
Localisation:
    Strings:
        - You must specify an option
        - The player you specified is not online
        - That player is already trading
        - You can't do that now!
        - Not your item
        - Invalid inventory
        - Trade cancelled
        - Confirming trade
        - Item duplication or loss detected, aborting trade
        - The trade could not be completed. Not enough room
        - Trade finished!
        - A player rejected the trade. Aborting.
        - Are you sure you want to trade
        - for
        - type /trade confirm to confirm, or /trade reject to reject
        - Trade request sent
        - Request declined
    