# Allows players to right click to initiate a trade request
RightClickTrade: true
# Force players to be within the specified distance to trade
RangeCheck:
    Enabled: true
    MaxDistance: 20
# Automatically check for updates on server startup
CheckForUpdates: true
# Log trades to the console
Verbose: true
# Send usage statistics to usage.blockface.org. You can also disable this, or choose to send stats anonymously, in /plugins/stats
Stats: true