name: LocalChat
author: Arkel (Oliver Brown)
main: net.ark3l.LocalChat.LocalChat
version: 1.2.1
depend: [Spout]
commands:
  trade:
    description: Trade with another player
    usage: /trade <player>